# Generated by Django 5.0.4 on 2024-04-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palavra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=100, unique=True)),
                ('significado', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Glossario',
        ),
    ]
