# Generated by Django 5.0.4 on 2024-04-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_palavra_delete_glossario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='foto',
            field=models.ImageField(default='.', upload_to='static/fotos'),
            preserve_default=False,
        ),
    ]
