# Generated by Django 5.0.4 on 2024-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cafe_aroma_cafe_intensidade_cafe_tamanho_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='favoritar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('cafe', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='cafe',
            name='aroma',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='intensidade',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='tamanho',
            field=models.CharField(max_length=120),
        ),
    ]
